- uclibc/Dockerfile.builder
Fixes #9
Closes #10
The patches in question were merged upstream (http://www.uclibc-ng.org/changeset/2ac8348609b63d6f3a87cb27ce17deff889c6a73/uclibc-ng and http://www.uclibc-ng.org/changeset/8c85b44f6ab42561207365f19b9d1fd69d960771/uclibc-ng), and are included in this latest 1.0.13 release (from 2016-03-13; yesterday). :smile:
cc @thockin @aledbf (wanna give this a go? :+1:)
> Set an explicit version of uClibc-ng, and bump it to the latest 1.0.13 release

- glibc/Dockerfile.builder
- musl/Dockerfile.builder
- uclibc/Dockerfile.builder
Closes #13
`CONFIG_LAST_SUPPORTED_WCHAR=0` amounts to `any valid printable Unicode character will be printed` (see https://github.com/docker-library/busybox/issues/13#issuecomment-252121558)
> Set CONFIG_LAST_SUPPORTED_WCHAR for better unicode input support

- uclibc/Dockerfile.builder
Origin one didn't get error because tar didn't specify the compression type (only `tar -xf` to let it detect the type), but it makes no sense to download `gz` file and name it `bz2`, btw, `bz2` is much smaller, so let's just download the bz2 tarball?
> Fix buildroot tarball extension type, should be bz2

- musl/Dockerfile.builder
Tail end of the `./build.sh musl` output:
```console
Step 16/16 : RUN cp -L /etc/resolv.conf rootfs/etc/ 	&& chroot rootfs /bin/sh -xec 'nslookup google.com' 	&& rm rootfs/etc/resolv.conf
---> Running in a9a77c9c2a8c
+ nslookup google.com
nslookup: can't resolve '(null)'
Name:      google.com
Address 1: 172.217.11.78 lax17s34-in-f14.1e100.net
Address 2: 2607:f8b0:4007:802::200e lax17s34-in-x0e.1e100.net
---> c56addf83f45
Removing intermediate container a9a77c9c2a8c
Successfully built c56addf83f45
+ docker run --rm busybox:musl-builder tar cC rootfs .
+ xz -z9
+ docker build -t busybox:musl musl
Sending build context to Docker daemon  627.2kB
Step 1/3 : FROM scratch
--->
Step 2/3 : ADD busybox.tar.xz /
---> eb4c56119b47
Removing intermediate container 1fd05035d650
Step 3/3 : CMD sh
---> …
```
> Update "musl" variant to Alpine 3.6

- glibc/Dockerfile.builder
Size comparison:
```console
$ docker images 'busybox:glibc*'
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             glibc-test          612b91ab525b        6 minutes ago       4.37MB
busybox             glibc               3aa1364bbd97        4 weeks ago         4.34MB
busybox             glibc-builder       267411c608af        6 minutes ago       211MB
```
> Update glibc's builder to stretch

- uclibc/Dockerfile.builder
Size comparison:
```console
$ docker images 'busybox:uclibc*'
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             uclibc-test         0eccf8eb8ac0        38 seconds ago      1.11MB
busybox             uclibc              c30178c5239f        4 weeks ago         1.11MB
busybox             uclibc-builder      a3cdccf65e96        48 seconds ago      2.73GB
```
(no difference, since the compiled bits should be identical given we pull everything important from buildroot, not the host image)
> Update uclibc's builder to stretch

- glibc/Dockerfile.builder
- uclibc/Dockerfile.builder
See https://github.com/docker-library/python/issues/236 for details.
> Swap from "gnupg2" to "gnupg"

- glibc/Dockerfile.builder
- musl/Dockerfile.builder
- uclibc/Dockerfile.builder
This parses the buildroot "device_table.txt" directly to both ensure the directories it specifies exist, and to apply the permissions it expects on the files they deem sensitive enough to explicitly note and update in their scripts.
> Make sure all the buildroot bits have appropriate upstream-supplied permissions

- glibc/Dockerfile.builder
- musl/Dockerfile.builder
- uclibc/Dockerfile.builder
See https://bugs.debian.org/913614
> Update "gpg" invocations to use "--batch"

- uclibc/Dockerfile.builder
Closes #71 
This depends initially on https://github.com/debuerreotype/docker-debian-artifacts/issues/84 and ultimately on https://github.com/docker-library/official-images/issues/6709.
I've tested it successfully via QEMU emulation, but have not been able to test/verify it on real hardware yet.
> Add initial mips64le support in uclibc

- .github/workflows/ci.yml
- .github/workflows/fake-gsl.sh
See https://github.com/docker-library/bashbrew/pull/2. :+1:
> Update GitHub Actions to take advantage of a generated matrix

- glibc/Dockerfile.builder
- musl/Dockerfile.builder
- uclibc/Dockerfile.builder
This is a test to see if https://github.com/docker-library/busybox/pull/81 is sufficient for testing bumps like this via PRs again! :smile:
> Update Buildroot to 2020.02.2

- glibc/Dockerfile.builder
- musl/Dockerfile.builder
- uclibc/Dockerfile.builder
Adds vim modeline ft comments to .builder files, which are assumed
to be Ruby files by various programs. This has the added benefit
of overriding the language for https://github.com/github/linguist/
without needing to add a .gitattributes file.
> fix: override filetype

- .github/workflows/ci.yml
- .github/workflows/fake-gsl.sh
- .github/workflows/munge-build.sh
- .github/workflows/munge-debian-unstable.sh
- Dockerfile-builder.template
- stable/uclibc/Dockerfile.builder
- unstable/uclibc/Dockerfile.builder
(to verify that Debian Ports arches like riscv64 are likely to continue working)
See also https://github.com/docker-library/oi-janky-groovy/blob/0f8796a8aeedca90aba0a7e102f35ea172a23bb3/tianon/busybox/arch-pipeline.groovy#L68-L71
> Add Debian Unstable to the CI builds

- Dockerfile-builder.template
- latest-1/glibc/Dockerfile.builder
- latest-1/musl/Dockerfile.builder
- latest-1/uclibc/Dockerfile.builder
- latest/glibc/Dockerfile.builder
- latest/musl/Dockerfile.builder
- latest/uclibc/Dockerfile.builder
This is meant to disable the optional, on-by-default hardware acceleration added in 1.36.0 to support the sha1sum and sha256sum functions. There is an issue where github actions hosted runners have processor feature sets that confuses acceleration detection. Alpine has also disabled this acceleration in their busybox package. Details in the issue below. Once the fix can be implemented upstream it would be ok to back this change out.
This is my first PR to docker-library so I don't know if I'm supposed to do something after editing the `Dockerfile-builder.template`.
closes: #166
> disable hwaccel closing issue with sha1sum and sha256sum

- Dockerfile-builder.template
- latest-1/glibc/Dockerfile.builder
- latest-1/uclibc/Dockerfile.builder
- latest/glibc/Dockerfile.builder
- latest/uclibc/Dockerfile.builder
This is pulled in automatically via `gnupg`, and moved from `Recommends` to `Depends` in https://salsa.debian.org/debian/gnupg2/-/commit/99474ad900a8bcdd0e7b68f986fec0013fc01470, which has been part of `src:gnupg2` since 2.1.21-4 (and every supported version of both Debian _and_ Ubuntu have 2.2.x 😇).
> Remove explicit `dirmngr` reference

- Dockerfile-builder.template
- latest/glibc/Dockerfile.builder
- latest/musl/Dockerfile.builder
- latest/uclibc/Dockerfile.builder
- versions.json
https://busybox.net/
> 19 May 2023 -- BusyBox 1.36.1 (stable)
> [BusyBox 1.36.1](https://busybox.net/downloads/busybox-1.36.1.tar.bz2). ([git](https://git.busybox.net/busybox/tree/?h=1_36_stable))
>
> Bug fix release. 1.36.1 has fixes for line editing, detection of hardware sha1/sha256 support, unzip (do not create suid/sgid files unless -K), shell (printf and sleep with no args, handing of SIGINT in sleep), ed.
(Although it looks like Git hasn't been updated yet -- no 1_36_1 tag nor relevant "releasing" commits in the linked branch :sweat_smile:)
> Update to 1.36.1

- latest-1/glibc/Dockerfile.builder
- latest-1/musl/Dockerfile.builder
- latest-1/uclibc/Dockerfile.builder
- latest/glibc/Dockerfile.builder
- latest/musl/Dockerfile.builder
- latest/uclibc/Dockerfile.builder
- versions.json
@LaurentGoderre this shouldn't actually change much (if anything) in our images, so we should save merging and rebuilding with this for when we're ready with your updated SBOM scanner changes :eyes:
> Update buildroot to 2023.11.1

- Dockerfile-builder.template
- latest-1/musl/Dockerfile.builder
- latest/musl/Dockerfile.builder
```console
$ docker run -it --rm --pull=always alpine:edge
edge: Pulling from library/alpine
Digest: sha256:67b8a3c4c19bbdd43de723881bc536758f5e780f8d32ef8f5ef2b72f769a3e78
Status: Image is up to date for alpine:edge
/ # apk add --no-cache --quiet curl
/ # curl --version
Error relocating /usr/lib/libcurl.so.4: SSL_get0_group_name: symbol not found
```
See https://github.com/alpinelinux/docker-alpine/issues/383 (and https://github.com/docker-library/busybox/pull/193)
> Add `apk upgrade libssl3 libcrypto3` as temporary Alpine Edge woes balm

- Dockerfile-builder.template
- latest-1/glibc/Dockerfile.builder
- latest/glibc/Dockerfile.builder
This allows us to build successfully on Debian Unstable again.
Fixes https://github.com/docker-library/busybox/issues/198
> Apply patch to remove CBQ functionality

- Dockerfile-builder.template
- latest-1/glibc/Dockerfile.builder
- latest-1/musl/Dockerfile.builder
- latest-1/uclibc/Dockerfile.builder
- latest/glibc/Dockerfile.builder
- latest/musl/Dockerfile.builder
- latest/uclibc/Dockerfile.builder
Apparently missing for ~5 years 🤦
This might cause some of our builds to fail which haven't been previously, but I guess they would do so in ways we should investigate. :see_no_evil:
> Add missing `set -e` to our `nslookup` smoke test 😭

- Dockerfile-builder.template
Oops, this should've been part of 349fb1ced29eba72048b7dfd36c0207c9f0eb376 (https://github.com/docker-library/busybox/pull/206) 🙈
> Remove some 1.35.x leftovers

- .patches/README.md
- .patches/no-cbq.patch
- .patches/sha1_process_block64_shaNI.patch
- Dockerfile-builder.template
- build.sh
- latest-1/glibc/Dockerfile.builder
- latest-1/musl/Dockerfile.builder
- latest-1/uclibc/Dockerfile.builder
- latest/glibc/Dockerfile.builder
- latest/musl/Dockerfile.builder
- latest/uclibc/Dockerfile.builder
This adds a directory for us to store patches we need to apply during build -- I've copied the "no CBQ" patch we've already been applying, and a new "sha1_process_block64_shaNI.patch" which applies a patch for our new non-x86 build failures (https://github.com/docker-library/busybox/pull/206#issuecomment-2384225988).
I've also added a README to the new patches directory to make it clear what types of patches are appropriate/acceptable (perhaps more accurately, why almost all patches are *not* acceptable).
This changes the build context for our rootfs builds to be the root of the repository so we don't have to muddy our template applying code with which patches to copy and can instead maintain that in the template itself (and skip the entire "patch applying" block of code when there are no …
> Add explicit "patches" directory

- Dockerfile-builder.template
- latest-1/glibc/Dockerfile.builder
- latest-1/musl/Dockerfile.builder
- latest-1/uclibc/Dockerfile.builder
- latest/glibc/Dockerfile.builder
- latest/musl/Dockerfile.builder
- latest/uclibc/Dockerfile.builder
- versions.sh
See https://git.busybox.net/buildroot/commit/?id=366d403bedd83d1e884b6c7c60a8a4ff497a458a (or rather, https://gitlab.com/buildroot.org/buildroot/-/commit/366d403bedd83d1e884b6c7c60a8a4ff497a458a -- or, if you prefer, the GitHub mirror at https://github.com/buildroot/buildroot/commit/366d403bedd83d1e884b6c7c60a8a4ff497a458a :joy:)
> Use GitLab for all buildroot references

- Dockerfile-builder.template
- latest-1/glibc/Dockerfile.builder
- latest-1/musl/Dockerfile.builder
- latest-1/uclibc/Dockerfile.builder
- latest/glibc/Dockerfile.builder
- latest/musl/Dockerfile.builder
- latest/uclibc/Dockerfile.builder
Without this fix, if we try to build i386 on an amd64 machine without the linux32 "personality" applied, it uses `uname -m` and gets a slightly different result due to the lack of https://git.busybox.net/busybox/tree/arch/i386/Makefile?h=1_37_stable#n7 (adding `-march` and `-mtune` values to builds).
If we set `ARCH` appropriately during build, that file gets sourced and our builds include the appropriate values.
This does *not* affect uclibc builds because they set `CROSS_COMPILE`, which overrides the value of `(SUB)ARCH` (although it would be valid to set both in all cases, to be explicit, I just don't think that's necessary).
> Fix reproducibility of non-uclibc i386 builds

- Dockerfile-builder.template
- latest-1/glibc/Dockerfile.builder
- latest-1/musl/Dockerfile.builder
- latest-1/uclibc/Dockerfile.builder
- latest/glibc/Dockerfile.builder
- latest/musl/Dockerfile.builder
- latest/uclibc/Dockerfile.builder
I moved too fast in https://github.com/docker-library/busybox/pull/216 and forgot to re-test amd64, which was ironically broken by my i386 fix, so now we do the full "distro arch to 'busybox arch'" conversion for the set of arches we support (which isn't *that* big).
> Fix i386 again, but correctly
